config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets, only: [:index, :show, :create, :new] do
    resources :appointments, only: [:create]
  end
  resources :appointments, only: [:index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :pet
  belongs_to :user
  # belongs_to :owner, through: :pet, foreign_key: :user_id

  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :message, presence: true
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :appointments, dependent: :destroy
  belongs_to :user
  SPECIES = ["Dog", "Cat", "Fish", "Hamster", "Bird", "Snake", "Frog", "Turtle", "Rabbit"]
  has_one_attached :picture
  validates :name, presence: true
  validates :species, presence: true, inclusion: { in: SPECIES }
  validates :address, presence: true
  validates :city, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pets
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.where(user: current_user)
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to appointments_path
  end

  def show
    @appointment = Appointment.find(params[:id])
    # @pet = Pet.find(params[:pet_id])
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.user = current_user
    @pet = Pet.find(params[:pet_id])
    @appointment.pet = @pet
    if @appointment.save
      redirect_to appointments_path
    else
      render "pets/show"
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date, :start_time, :end_time, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @pets = Pet.all
    if params[:query].present?
      sql_query = "species ILIKE :query OR city ILIKE :query"
      @pets = Pet.where(sql_query, query: "%#{params[:query]}%")
    else
      @pets = Pet.all
    end
  end

  def show
    @pet = Pet.find(params[:id])
    @appointment = Appointment.new
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :species, :address, :city, :description, :picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/index.html.erb
<div class="container-index-appointments" >
  <h2 style="text-align: center; padding: 30px; font-family: 'Poppins'">All your Snuggle Sessions</h2>
    <!-- <div class="card-product"> -->
      <% @appointments.each do |appointment| %>

        <div class="card-appointment" >
          <div class="card-image">
            <%= cl_image_tag appointment.pet.picture.key, height: 200, width: 200, crop: :fill %>
          </div>


          <div class="card-body" style="margin-top: 28px">
            <p style="font-size: 20px; color: black"> <%= appointment.pet.name.capitalize %> </p>
            <p style="color: black"> <strong>Date of the snuggle:</strong> <%= appointment.date.to_s(:long_ordinal) %> </p>
            <p style="color: black"> <strong>Start time:</strong>  <%= appointment.start_time.strftime('%H:%M') %> </p>
            <p style="color: black"> <strong>End time:</strong>  <%= appointment.end_time.strftime('%H:%M') %> </p>

            <div class="btn-app">
                <%= link_to "View Snuggle", appointment_path(appointment) %>
            </div>
            <div class="btn-app">
                <%= link_to "Cancel Snuggle", appointment_path(appointment), method: :delete %>
            </div>
          </div>
        </div>
      <% end %>
</div>

app/views/appointments/show.html.erb
  <div id="card-show-appo" class="card mb-4" style="width: 28%; margin: auto; margin-top: 30px">
    <div id="textappo">
      <h2 style="font-family: 'Poppins'">Snuggle session with <%= @appointment.pet.name %> </h2>
      <p style="font-family: 'Poppins'; font-size: 14px"> <%= @appointment.pet.description %> </p>
      <p style="font-family: 'Poppins'"><strong> ADDRESS:</strong> <%= @appointment.pet.address %> </p>
      <p style="font-family: 'Poppins'"><strong> DATE:</strong> <%= @appointment.date.to_s(:long_ordinal) %> </p>
      <p style="font-family: 'Poppins'"><strong> TIME: From <%= @appointment.start_time.strftime('%H:%M') %> to <%= @appointment.end_time.strftime('%H:%M') %> </p>
    </div>
    <div id="imgappo">
      <div class="card-image-pet" style="width: 80%, text-align: center">
        <%= cl_image_tag @appointment.pet.picture.key, height: 200, width: 200, crop: :fill %>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookAPet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class= "page-container">
      <div class="content-container">
        <%= yield %>
      </div>
      <div class="footer-container">
        <%= render 'shared/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<section class="main-container">
  <div class="description">
    <h1>You cannot have an animal but would like to spend some time with them?
    </h1>
  </div>

  <div class="flex-container">
    <div class="flex-items">
      <%= image_tag("cat.png", :alt => "cat") %>
      <p class= "pt-2">Choose a pet</p>
    </div>
    <div class="flex-items">
       <%= image_tag("chat.png", :alt => "chat") %>
       <p class= "pt-2">Reach the owner</p>
    </div>
    <div class="flex-items">
       <%= image_tag("hugging-dog.png", :alt => "hugging dog") %>
       <p class= "pt-2">Set up your <br> snuggle session</p>
    </div>
  </div>
</section>

  <div class="btn-wrapper">
  <%= link_to 'Find a pet', pets_path, :class => "btn" %>
  </div>

<section class="main-container">
  <div class="description">
    <h1>You don’t have enough time to play with your pet?
    </h1>
  </div>

  <div class="flex-container">
    <div class="flex-items">
      <%= image_tag("glass.png", :alt => "search") %>
      <p class= "pt-2">Find a local pet lover</p>
    </div>
    <div class="flex-items">
       <%= image_tag("chat.png", :alt => "chat") %>
       <p class= "pt-2">Get in touch</p>
    </div>
    <div class="flex-items">
       <%= image_tag("pets.png", :alt => "pets") %>
       <p class= "pt-2">Share your pet</p>
    </div>
  </div>
</section>

  <div class="btn-wrapper pb-5">
    <%= link_to 'Share your pet', new_pet_path, :class => "btn" %>
  </div>

app/views/pets/_form.html.erb
<div class="container">
  <div class="form mt-3">
    <h1 class="mb-3"> Pet sharing is caring 🦕</h1>
    <%= simple_form_for(@pet) do |f| %>
      <%= f.input :name %>
      <%= f.input :species, collection: Pet::SPECIES %>
      <%= f.input :address %>
      <%= f.input :city %>
      <%= f.input :description %>
      <%= f.input :picture, as: :file %>
      <%= f.submit "Share your pet", class: "btn btn-block mt-3" %>
    <% end %>
  </div>
</div>

app/views/pets/index.html.erb
<%= render 'shared/banner_index' %>
<!-- <div class="container-title>
  <h2>All our amazing pets</h2>
</div> -->
<div class="container-sm container-pets-index">

  <% @pets.each do |pet| %>
    <div class="card" style="width: 288px;">
      <div class="card-image-pet">
        <% if pet.picture.attached? %>
          <%= cl_image_tag pet.picture.key, height: 200, width: 200, crop: :fill %>
        <% end %>
      </div>
      <div class="card-body">
        <h3 class="pl-2"> <%= pet.name.capitalize %></h3>
        <div class="card-text-pet">
          <p class="card-text"> <strong>Species</strong>: <%= pet.species %> </p>
          <p class="card-text"> <strong>City</strong>: <%= pet.city %> </p>
        </div>
      </div>
      <%= link_to "", pet_path(pet), class: 'card-link' %>
    </div>
  <% end %>
  <!-- container -->
</div>
<div class="container">
  <div class="btn-center" style="justify-content: center;">
    <%= link_to "Share your Pet", new_pet_path %>
  </div>
</div>

app/views/pets/new.html.erb
<%= render 'form' %>
<div class="text-center my-3">
  <%= link_to "Back to all our pets", pets_path, class: "text-muted" %>
  </div>

app/views/pets/show.html.erb
<div class="container">
    <div class="pet-flex">
        <div class="pet-information">
          <% if @pet.picture.attached? %>
            <%= cl_image_tag @pet.picture.key, height: 300, width: 250, class: "pet-pic", crop: :fill %>
          <% end  %>
          <div class="pet-text">
            <h3> Hello there, I am <%= @pet.name %> </h3>
            <br>
            <p> <strong>About me:</strong> <%= @pet.description %></p>
            <p> <strong>Species:</strong> <%= @pet.species %> </p>
            <p> <strong>Address:</strong> <%= @pet.address %> </p>
            <p> <strong>City:</strong> <%= @pet.city %> </p>
          </div>
        </div>

        <div class="appointment-form">
          <h3>Schedule a Snuggle Session with <%= @pet.name %> </h3>
          <%= simple_form_for([@pet, @appointment]) do |f| %>
            <%= f.input :date %>
            <%= f.input :start_time, as: :time, :minute_step => 15 %>
            <%= f.input :end_time, as: :time, :minute_step => 15 %>
            <%= f.input :message %>
            <%= f.button :submit, "Schedule snuggle session", class: "btn btn-block" %>
          <% end %>
        </div>
    </div >
  <%= link_to "Back to all our pets", pets_path, class: "text-muted" %>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,-0.6),rgba(0,0,0,-0.6)), url(<%= asset_url "banner.jpg"%>)">
  <div class="container">
      <%= form_tag pets_path, class: "search-bar form-inline", method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control searchbar",
          placeholder: "Find a pet"
        %>
        <%= submit_tag "Search", class: "btn" %>
      <% end %>

    <div class="banner-title">
      <h1>Petsharing</h1>
    </div>
  </div>

  <!-- <div class="container d-flex">
    <div class="search-bar">
      <div class="box box1">where</div>
      <div class="box box2">species</div>
      <div class="box">owner</div>
    </div>
    <div class="btn btn-primary">Search</div>
  </div> -->

</div>

app/views/shared/_banner_index.html.erb
<div class=" banner banner-index" style="background-image: linear-gradient(rgba(0,0,0,-0.6),rgba(0,0,0,-0.6)), url(<%= asset_url "banner_index.jpg"%>)">
  <div class="container">
      <%= form_tag pets_path, class: "search-bar form-inline", method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control searchbar",
          placeholder: "Find a pet"
        %>
        <%= submit_tag "Search", class: "btn" %>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <!-- Footer -->
  <footer class="footer-container">
    <div class="footer">
    <!-- Copyright -->
      <div class="footer-links">© 2020 Copyright:
        <a href="https://www.lewagon.com"> PaBrJuCa - Le Wagon Batch 490 </a>
      </div>
      <!-- Copyright -->

      <!-- Social buttons -->
      <div class="footer-links">
        <a href="https://github.com/camimurg/book-a-pet"><i class="fab fa-github"></i></a>
        <a href="https://www.instagram.com/lewagongermany/"><i class="fab fa-instagram"></i></a>
        <a href="https://www.facebook.com/lewagongermany"><i class="fab fa-facebook"></i></a>
        <a href="https://twitter.com/LeWagonGermany"><i class="fab fa-twitter"></i></a>
      </div>
      <!-- Social buttons -->
    </div>
  </footer>
  <!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "🦕 Petsharing", "/", class: "navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Pets", pets_path(@pets), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Snuggle Sessions", appointments_path(@appointments), class: "nav-link" %>
      </li>
      <li>
        <a href="#" class="nav-item nav-link"> About us </a>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "pprofile_pic.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>